### ISSUE TITLE
Extend the fix implemented on TweakScaleCompanion_NF#2 to every Companion

### ISSUE THREAD

**Issue by Lisias** [TweakScale/Companion#15]
At the tittle says.

Source: https://github.com/net-lisias-ksp/TweakScaleCompanion_NF/issues/2

**Comment by 7ranceaddic7** [comment]
let me do this for you

**Comment by Lisias** [comment]
> let me do this for you

I will be thankful - if you agree with the licensing terms (that double license stunt of GPLv2 and SKLv1). Make the pull requests against the DEV branches, please.

Also mention the URL of this issue on the commits, so I can keep track of the reason of the changes.

To tell you the true, what I have published is only about 40% of the total patches I'm writing. I was advised to prevent publishing too much unfinished patches to avoid people running up to write bad patches just to get on SpaceDock and CKAN sooner, so I'm just publishing a few bunch to test some concepts. The real load of patches will be published after I stabilize things enough to allow 2.4.4 to go to the wild without killing me on the process. :)

**Comment by 7ranceaddic7** [comment]
I'll look to the commits you've already provided as templating.

**Comment by Lisias** [comment]
Implemented on the following commits (from multiple Companions):

* https://github.com/net-lisias-ksp/ImpossibleInnovations/commit/b306a628a4a3f979c99cbce22de6df9739e9e9de
* https://github.com/TweakScale/Companion_Multipass/commit/8f3498094a50a83ddd283da96e8dbeb6a207d6ce
* https://github.com/TweakScale/Companion_OPT/commit/3ebad1aa6b76f220aaa0e8a0ab104fc34e5e4ab6
* https://github.com/TweakScale/Companion_Rockets/commit/24221d22bc97b50c00d3c8728932aa826ddb081e
* https://github.com/TweakScale/Companion_SMCE/commit/a901cad53adc6488b0e3793407389e0ce002e377

**Comment by Lisias** [comment]
Post mortem: ended up reworking some add'ons, as the current fix is faster  due the `:NEEDS` completely removing the patch before the patch process.

* https://github.com/TweakScale/Companion_APP/commit/98475f8211ad14338f14608a5a70477aa3a23470
* https://github.com/TweakScale/Companion_FS/commit/6576b7849a2a1935b8a86a73cb4be80c879c363d
* https://github.com/TweakScale/Companion_Frameworks/commit/f6cc3b69ed1e5b355c418a9dbadd3839305cba88
* https://github.com/TweakScale/Companion_KIAS/commit/d787254994a92c2f8c6e5a446851419ea4923629
* https://github.com/TweakScale/Companion_LivingStyle/commit/10cf3556b5d8b473086cbd7c0cf2f3d0bb3475c2
* https://github.com/TweakScale/Companion_PKMC/commit/89373a8f3e62621aa107ab1b493786d0f5931f2e
* https://github.com/TweakScale/Companion_SMCE/commit/5a7eb76c99e67159b1b9aa5afb96eb71517dae84
* https://github.com/TweakScale/Companion_US/commit/0859785784f25d3079644d39c5c1d19ddd857217
