### ISSUE TITLE
combination changes tanks capacity

### ISSUE THREAD

**Issue by Jammer-TD** [TweakScale/Companion#18]
I have had an issue in which, when using mod "Configuable Containers" I find tanks like (kwr/spacey-Y) have a unique capacity gain using TweakScale.
I haven't noticed it happen on all parts but it's messing with my new craft build(wieght balance). See Demo:
http://www.teamdemonic.com/photo/KSP/2021/error/KSP-TS-Containers_error.mp4
when config containers is removed the problem goes away(however saved craft is screwed with the new amount).
I have bench tested and here are the logs and data
[ts2446-1.11.2-05.zip](https://github.com/net-lisias-ksp/TweakScaleCompanion/files/6253129/ts2446-1.11.2-05.zip)
thanks
Jammer

**Comment by Jammer-TD** [comment]
left on wrong thread

**Comment by Lisias** [comment]
To tell you the true, you almost got it on the right place.

Configurable Containers will be handled on the https://github.com/net-lisias-ksp/TweakScaleCompantion_FuelSwitches. :)
