### ISSUE TITLE
Version file in the new version is still reading as the old version. when installed from the release page.

### ISSUE THREAD

**Issue by ned228** [TweakScale/Companion#24]
The version information for the new build is still the same as the previous build. So when I install it keeps saying that there is an update when I have already installed it. Had to change the version manually to get it to stop mentioning updates.

**Comment by Lisias** [comment]
Embarrassing. I'm fixing the mess now.

**Comment by Lisias** [comment]
Fixed and deployed.

Thanks for the heads up, @ned228 ! Cheers!
