### ISSUE TITLE
RELEASE/2024.07.13.0 has old version file

### ISSUE THREAD

**Issue by kretze** [TweakScale/Companion#34]
TweakScaleCompanion.version
Old Version File

	"VERSION":{
		"MAJOR":2024,
		"MINOR":02,
		"PATCH":20,
		"BUILD":0
		},

**Comment by Lisias** [comment]
🤦 

Fixing it.

Thanks for the heads up, @kretze !

**Comment by Lisias** [comment]
Fixed. Thank you!
